name: Build

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - run: npm i

      - name: Build
        run: npm run build

      - name: Add & commit build files
        uses: EndBug/add-and-commit@v4.2.0
        with:
          add: Platforms/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
