name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build Styles
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - run: npm i

      - name: Build
        run: npm run build

      - name: Add & commit build files
        uses: EndBug/add-and-commit@v4.2.0
        with:
          add: Platforms/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test-ios:
    name: Test iOS Output
    needs: build
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2

      - name: Switch to Xcode 11
        run: ls /Applications; sudo xcode-select -s /Applications/Xcode_11.5.app

      - run: swift package generate-xcodeproj

      - name: Cache build
        uses: actions/cache@v1
        with:
          path: ./.build
          key: ${{ runner.os }}-${{ hashFiles('./Platforms/iOS/**/*.swift') }}

      - run: xcodebuild -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8,OS=13.5' -scheme QuartzStyles-Package test  | xcpretty --test --color
