name: Test

on:
  pull_request:
    branches:
      - master

jobs:
  iOS:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2

      - name: Switch to Xcode 11
        run: ls /Applications; sudo xcode-select -s /Applications/Xcode_11.5.app

      - run: swift package generate-xcodeproj

      - name: Cache build
        uses: actions/cache@v1
        with:
          path: ./.build
          key: ${{ runner.os }}-${{ hashFiles('./Platforms/iOS/**/*.swift') }}

      - run: xcodebuild -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8,OS=13.5' -scheme QuartzStyles-Package test  | xcpretty --test --color
